version: 1.0.{build}

image:
  - Visual Studio 2017

cache:
  - C:\sdl_root
  - '%LOCALAPPDATA%\pip\Cache'

configuration:
  - Release

platform:
  - x64

environment:
  PYTHON: "C:\\Python27"
  QTDIR: "C:\\Qt\\5.10.1\\msvc2017_64\\"
  PATCH_VER: "%APPVEYOR_REPO_COMMIT%"

install:
  - cmd: git submodule update --init --recursive
  - cmd: set PATH=%PATH%;%QTDIR%;%QTDIR%\\bin;%PYTHON%/Scripts/
  # Conan
  - cmd: pip.exe install conan --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: pip.exe install conan_package_tools --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: refreshenv
  - cmd: conan user # It creates the conan data directory
  # SDL2
  - ps: |
      $SDL_VERSION = "2.0.4"
      $SDL_PREFIX = "C:\sdl_root\SDL2-$SDL_VERSION"
      if (!(Test-Path -Path $SDL_PREFIX)) {
        Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
        7z x SDL2-devel-$SDL_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_INCLUDE_DIR = "$SDL_PREFIX\include"
      $env:SDL2_LIBRARY = "$SDL_PREFIX\lib"
      $env:SDL2_PATH = "$SDL_PREFIX"

before_build:
  - cmd: conan remote add yage https://api.bintray.com/conan/bentoudev/yage
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: msbuild /version
  - cmd: mkdir Build && cd Build
  - cmd: conan install ..
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DSDL2_PATH=%SDL2_PATH% -DCMAKE_PREFIX_PATH=%QTDIR% -DYAGE_VERSION_PATCH=%PATCH_VER% ..

build:
  project: C:\projects\yage\Build\ALL_BUILD.vcxproj
  verbosity: minimal
  parallel: true

test_script:
  - cmd: C:\projects\yage\Build\bin\CoreTests.exe -r junit > CoreTests.xml
  - cmd: C:\projects\yage\Build\bin\UtilsTests.exe -r junit > UtilsTests.xml

on_success:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\CoreTests.xml))
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\UtilsTests.xml))
