language: cpp

os:
  - linux

sudo: required
dist: trusty

compiler:
  - clang
  - gcc
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - git submodule update --init --recursive

install:
  - $CXX --version
  - cmake --version

before_script:
  - mkdir Build && cd Build
  - cmake ..

script:
  - make
