language: cpp

os:
  - linux

sudo: required

compiler:
  - clang
  - gcc

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get -y purge cmake
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get -y install cmake
  - $CXX --version
  - cmake --version

before_script:
  - mkdir Build && cd Build
  - cmake ..

script:
  - make
