language: cpp
sudo: required
dist: trusty

os:
  - linux

addons:
  apt:
    packages:
    - gcov
    - xorg-dev
    - libxxf86vm-dev
    - libglu1-mesa-dev

compiler:
  - clang
  - gcc
  
before_install:
  - git submodule update --init --recursive

install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar xf cmake-3.3.2.tar.gz
  - cd cmake-3.3.2
  - ./configure
  - make
  - sudo make install
  - cd ..
  - $CXX --version
  - cmake --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer
  - cmake -DENABLE_COVERAGE=On --target all .

script:
  - ls
  - make

after_success:
  - make test
  - make gcov
  - bash <(curl -s https://codecov.io/bash) -X gcov