language: cpp

os:
  - linux

sudo: required
dist: trusty

compiler:
  - clang
  - gcc
  
before_install:
  - git submodule update --init --recursive

install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar xf cmake-3.3.2.tar.gz
  - cd cmake-3.3.2
  - ./configure
  - make
  - sudo make install
  - $CXX --version
  - cmake --version

before_script:
  - mkdir Build && cd Build
  - cmake --target all ..

script:
  - cd Build && make