language: cpp

compiler:
  - clang
  - gcc

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

before_install:
  - git submodule update --init --recursive

before_script:
  - mkdir Build && cd Build
  - cmake ..

script:
  - make