language: cpp

notifications:
  email: false

sudo: false
dist: trusty

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: clang
      script:
        - docker run -it -v $PWD:/src --workdir /src bentou/ubuntu-bionic-dev sh ./Scripts/build_clang.sh

    - os: linux
      compiler: gcc
      script:
        - docker run -it -v $PWD:/src --workdir /src bentou/ubuntu-bionic-dev sh ./Scripts/build_gcc.sh
      after_success:
        - docker run -it -v $PWD:/src --workdir /src bentou/ubuntu-bionic-dev sh ./Scripts/run_tests.sh
        - bash <(curl -s https://codecov.io/bash) -X gcov

# before_install:
# enable this for vulkan support
#  - wget https://s3-us-west-2.amazonaws.com/prod.lunarx/sdk/1457744859783_vulkansdk-linux-x86_64-1.0.5.0.run?AWSAccessKeyId=AKIAJ2OMJY5KDUYV55GA&Expires=1458999290&Signature=mU%2BOkmFcbx5ryz3HwgZ%2F7of%2Fkw8%3D

before_script:
  - export PATCH_VER=$TRAVIS_COMMIT
  - docker pull bentou/ubuntuartfuldev
  - docker ps -a
  - mkdir Build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer
