language: cpp

os:
  - linux

sudo: required
dist: trusty

compiler:
  - clang
  - gcc
  
addons:
  apt:
    sources:
      - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    packages:
      - cmake
      - cmake-data

before_install:
  - git submodule update --init --recursive

install:
  - $CXX --version
  - cmake --version

before_script:
  - mkdir Build && cd Build
  - cmake ..

script:
  - make
