language: cpp

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - gcov
    - xorg-dev
    - libxxf86vm-dev
    - libglu1-mesa-dev

matrix:
  include:
    - os: linux
      compiler: clang
      before_script:
        - cmake --target all .

    - os: linux
      compiler: gcc
      before_script:
        - cmake -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage " -DENABLE_COVERAGE=On --target all .
      after_success:
        - make test
        - make gcov
        - bash <(curl -s https://codecov.io/bash) -X gcov

before_install:
  - git submodule update --init --recursive

install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar xf cmake-3.3.2.tar.gz
  - cd cmake-3.3.2
  - ./configure
  - make
  - sudo make install
  - cd ..
  - $CXX --version
  - cmake --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer

script:
  - make
