version: 1.0.{build}

cache:
  - C:\sdl_root
#  - Dependencies

configuration:
  - Release

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.7\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin
  # SDL2
  - ps: |
      $SDL_VERSION = "2.0.4"
      $SDL_PREFIX = "C:\sdl_root\SDL2-$SDL_VERSION"
      if (!(Test-Path -Path $SDL_PREFIX)) {
        Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
        7z x SDL2-devel-$SDL_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_INCLUDE_DIR = "$SDL_PREFIX\include"
      $env:SDL2_LIBRARY = "$SDL_PREFIX\lib"
      $env:SDL2_PATH = "$SDL_PREFIX"

before_build:
  - msbuild /version
  - mkdir Build && cd Build
  - cmake ..

build:
  project: C:\projects\yage\Build\ALL_BUILD.vcxproj
  verbosity: minimal
  parallel: true

test_script:
  - cmd: C:\projects\yage\Build\Source\Core\Release\CoreTests.exe --gtest_output=xml:CoreTests.xml
  - cmd: C:\projects\yage\Build\Source\Utils\Release\UtilsTests.exe --gtest_output=xml:UtilsTests.xml
on_success:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\CoreTests.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\UtilsTests.xml))
