version: 1.0.{build}

#cache:
#  - Dependencies

configuration:
  - Release

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.7\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
  - msbuild /version
  - mkdir Build && cd Build
  - cmake ..

build:
  project: C:\projects\yage\Build\ALL_BUILD.vcxproj
  verbosity: minimal
  parallel: true

test_script:
  - cmd: C:\projects\yage\Build\Source\Core\Release\CoreTests.exe --gtest_output=xml:CoreTests.xml
  - cmd: C:\projects\yage\Build\Source\Utils\Release\UtilsTests.exe --gtest_output=xml:UtilsTests.xml
on_success:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\CoreTests.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\UtilsTests.xml))
