version: 1.0.{build}

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir Build && cd Build
  - cmake ..

build:
  project: C:\projects\volkhvy\Build\ALL_BUILD.vcxproj
  parallel: true

test_script:
  - cmd: C:\projects\volkhvy\Build\Source\Core\Release\CoreTests.exe --gtest_output=xml:CoreTests.xml
  - cmd: C:\projects\volkhvy\Build\Source\Utils\Release\UtilsTests.exe --gtest_output=xml:UtilsTests.xml
on_success:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\CoreTests.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\UtilsTests.xml))
